[supabase]
url="https://bbwcsefcjpnuwxltcdbu.supabase.co"
key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJid2NzZWZjanBudXd4bHRjZGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1ODcyNTcsImV4cCI6MjA4MzE2MzI1N30.Anf2nBetSFR0M6KJu0Nct8BORc-1OWclbzYdps0eSZQ"

[notice_board]
access_code = "YA_tnc"
