[supabase]
url="https://bbwcsefcjpnuwxltcdbu.supabase.co"
key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJid2NzZWZjanBudXd4bHRjZGJ1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzU4NzI1NywiZXhwIjoyMDgzMTYzMjU3fQ.WoFWiyabZPo4dTx0R35GHwIOsaMc5mHx2fdVpK2Z4iE"

[notice_board]
access_code = "YA_tnc"
